apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-backend-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
    - name: gitops-repo-url
    - name: image-name
    - name: image-tag
  tasks:
    - name: clone-code
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-java
      runAfter: [clone-code]
      taskRef:
        name: maven-build
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-push-image
      runAfter: [build-java]
      taskRef:
        name: kaniko-docker-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
    - name: update-gitops
      runAfter: [build-push-image]
      taskRef:
        name: gitops-yaml-update
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: gitops-repo-url
          value: $(params.gitops-repo-url)
        - name: file-to-update
          value: "deployment-java.yaml"
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: angular-frontend-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
    - name: gitops-repo-url
    - name: image-name
    - name: image-tag
  tasks:
    - name: clone-code
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-angular
      runAfter: [clone-code]
      taskRef:
        name: npm-build
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-push-image
      runAfter: [build-angular]
      taskRef:
        name: kaniko-docker-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
    - name: update-gitops
      runAfter: [build-push-image]
      taskRef:
        name: gitops-yaml-update
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: gitops-repo-url
          value: $(params.gitops-repo-url)
        - name: file-to-update
          value: "deployment-angular.yaml"
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-backend-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
    - name: gitops-repo-url
    - name: image-name
    - name: image-tag
  tasks:
    - name: clone-code
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-push-image
      runAfter: [clone-code]
      taskRef:
        name: kaniko-docker-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
    - name: update-gitops
      runAfter: [build-push-image]
      taskRef:
        name: gitops-yaml-update
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: gitops-repo-url
          value: $(params.gitops-repo-url)
        - name: file-to-update
          value: "deployment-python.yaml"
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
